### ISSUE TITLE
future of dopy (fork?)

### ISSUE THREAD

**Issue by kontrafiktion** [Wiredcraft/dopy#49]
Dopy seems to be sleeping again (https://github.com/Wiredcraft/dopy/issues/22).
I contacted @zbal in Feb. 2015 and he offered to add more committers. I declined then,
because my immediate concern was resolved. But now I would really like to see tag support
(https://github.com/Wiredcraft/dopy/pull/48) added because I am eagerly waiting to add this to Ansible.

I would gladly help out reviewing PRs and committing. I am not quite sure how easy it is to share the responsibility for uploading new versions to PyPi.

If this does not work, I propose to create a "dopy2". 
And I would completely rip out the DigitalOcean V1 API.

What do you think? 
Pinging @regentgal and @zyegfryed

**Comment by zbal** [comment]
@kontrafiktion - I will add you as a contributor to dopy - no problem. 

Tearing it appart and removing V1 was already in the pipe, just never had the time to complete / review. (see https://github.com/Wiredcraft/dopy/tree/refactor)

Lots of work needed indeed:
- full unit testing
- revamp (currently messy)
- removing old V1
- etc.

I simply do not have time at the moment. 

We'll be merging a few PR today and so on and push a new release out there. 

Let's see how the collaboration could go on, and I can also consider giving you access to pypi.

**Comment by kontrafiktion** [comment]
thanks for the trust

I started to adapt the Ansible digitalocean module to use tags as well.
(creating and deleting tags already works)
Did you already work on that? Just that we don't duplicate efforts.

**Comment by kontrafiktion** [comment]
I will merge at least the tags pull request and bump the version number to 0.3.8 until end of week

**Comment by regentgal** [comment]
i was pretty close to creating a fork myself and/or rewriting the ansible modules to use one of the other maintained digital ocean python libraries. i'm happy to help to keep this one alive. i'm not much of a python person either, but I can learn.

**Comment by atulhm** [comment]
@ kontrafiktion I see that you may have already started on adding tags support to the core module.  Don't want to duplicate effort.  Anyway I can help?

**Comment by kontrafiktion** [comment]
see https://github.com/ansible/ansible-modules-core/issues/4117#issuecomment-233181812
